Use the Application-Defined User Class instead of `Spree::User`
solidusio-contrib/solidus_social pull request #34
Opened 2017-08-08 02:52 UTC by pmn4

not an issue in most cases, but seems like the right thing to do.

_(there are some failing tests, but they seem to be failing on the parent commit as well)_

2017-08-15 16:48 UTC, jarednorman requested changes
Can we revert the changes to the specs so they still include the explicit class? Tests should avoid "computed" values to reduce the risk of false positives, `Spree.user_class` should always be `Spree::User` in our test suite.

2017-08-16 14:36 UTC, pmn4 commented
💯 great point.

2017-08-16 17:57 UTC, pmn4 commented on app/controllers/spree/omniauth_callbacks_controller.rb
> +      user = Spree.user_class.find_by_email(auth_hash['info']['email']) || Spree.user_class.new
@jarednorman I am having second thoughts about the first change on this line too. Is it safe to assume that the class defined by `Spree.user_class` inherits from `Spree::User`? If so, I am going to revert to:
``` ruby
Spree::User.find_by_email(auth_hash['info']['email']) || Spree.user_class.new
```

2017-08-16 18:00 UTC, pmn4 commented on app/controllers/spree/omniauth_callbacks_controller.rb
> +      user = Spree.user_class.find_by_email(auth_hash['info']['email']) || Spree.user_class.new
nevermind. `Spree::LegacyUser` doesn't even inherit from `Spree::User`

2017-08-16 20:16 UTC, merged